# Generated by Django 3.1.7 on 2021-03-31 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dName', models.CharField(max_length=100, unique=True)),
                ('os_version', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=10, verbose_name='device Type')),
                ('iems', models.CharField(max_length=50, unique=True)),
                ('is_home', models.IntegerField(choices=[('借出', 1), ('在库', 0)], max_length=5)),
                ('remarks', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('out_time', models.DateTimeField(max_length=50)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
    ]
