# Generated by Django 3.1.7 on 2021-03-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSManagement', '0002_phonemanage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemanage',
            old_name='iems',
            new_name='imei',
        ),
    ]
